CREATE TABLE CUSTOMER(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100)
);

CREATE TABLE PRODUCT(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100),
	PRICE NUMERIC(15,2)
);

CREATE TABLE PEDIDO(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CUSTOMER_ID INTEGER REFERENCES CUSTOMER (ID),
	DATA_PEDIDO TIMESTAMP,
	TOTAL NUMERIC(15,2)
);

CREATE TABLE ITEM_PEDIDO(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
	PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
	QUANTIDADE INTEGER
);